### ISSUE TITLE
Throws ValueError exception

### ISSUE THREAD

**Issue by singhj** [Red-devilz/hidden_markov#1]
Hello, I'm trying to work with the example in [Data-Intensive Text Processing with MapReduce](http://lintool.github.io/MapReduceAlgorithms/index.html) by Jimmy Lin and Chris Dyer, Section 6.2 (figure 6.3).

The HMM has been initialized as follows:
```
>>> import numpy as np
>>> from hidden_markov import hmm
>>> states = ('det', 'adj', 'nn', 'v')
>>> start_probability = np.matrix('0.5 0.1 0.3 0.1')
>>> transition_probability
matrix([[0. , 0.3, 0.7, 0. ],
        [0. , 0.2, 0.7, 0.1],
        [0. , 0.1, 0.4, 0.5],
        [0.5, 0.2, 0.2, 0.1]])
>>> emission_probability
matrix([[0.7 , 0.3 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.1 , 0.4 , 0.4 , 0.1 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.3 , 0.2 , 0.2 , 0.1 , 0.1 , 0.1 , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.3 , 0.2 , 0.1 , 0.19, 0.01]])
>>> possible_observation
('the', 'a', 'green', 'big', 'old', 'might', 'book', 'plants', 'people', 'person', 'john', 'wash', 'washes', 'loves', 'reads', 'books')
lin_hmm = hmm(states,possible_observation,start_probability,transition_probability,emission_probability)
```
The forward algorithm works correctly as expected:
```
>>> lin_hmm.forward_algo(('john', 'might', 'wash', ))
0.00018000000000000004
```
However, the training algorithm fails for the following observations:
```
>>> observation_tuple
[('john', 'might', 'wash'), ('john', 'loves'), ('john', 'reads', 'people'), ('a', 'person', 'loves', 'book')]
>>> quantities_observations = [1000, 2000, 3000, 5000]
>>> emission,transition,start = lin_hmm.train_hmm(observation_tuple, 1000, quantities_observations)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j_singh/.local/lib/python3.5/site-packages/hidden_markov/hmm_class.py", line 349, in train_hmm
    emProbNew = emProbNew/ em_norm.transpose()
ValueError: operands could not be broadcast together with shapes (4,16) (1,4) 
>>> 
```
Any thoughts? Thanks in advance.

**Comment by marquesslewis** [comment]
Having the same issue as @singhj.  Implementing the example Baum-Welch works, but when the number of observable states is greater than the hidden states, then training algorithm fails.  Anyone have any success or suggested patches?  I'll see if I can find a solution.

**Comment by YaoChungLiang** [comment]
I just comment out the transpose, and everything works fine.
![image](https://user-images.githubusercontent.com/42062593/59402007-9862f400-8d51-11e9-8d58-ad3fdac2b5c0.png)

**Comment by rahul13ramesh** [comment]
I wrote these algorithms a while back and haven't really maintained it since. However, #3 should fix the mentioned issue.
